title: Leon Hounnou
baseURL: https://github.com/Hounnou/Project3
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: Leon Hounnou
    weight: 1
  #fr:
    #contentDir: content/fr
    #title: Leon Hounnou
    #weight: 2
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  background_color_class: bg-black
  description: The last theme you'll ever need. Maybe.
  #facebook: https://www.facebook.com/leon.hounnou/
  favicon: ''
  featured_image: /images/gohugo-default-sample-hero-image.jpg
  github: 'https://github.com/Hounnou?tab=repositories'
  gitlab: ''
  instagram: ''
  linkedin: https://linkedin.com/in/hounnouleon
  mastodon: ''
  recent_posts_number: 2
  rss: ''
  site_logo: ''
  slack: ''
  stackoverflow: ''
  twitter: 
  youtube: ''

markup:
  goldmark:
    renderer:
      unsafe: true
